### ISSUE TITLE
About MRI 

### ISSUE THREAD

**Issue by Edenkut** [farrell236/SVRnet#1]
Hi. I plan to use the 2D MRI slices(256,256,150) to reconstruct the 3D. 
Is it possible to use SVRnet?
It seems that you use natural images.

**Comment by farrell236** [comment]
Hi Edenkut, We do train the network on medical images, but unfortunately we are not allowed to release the data/model due to patient privacy. However, we have released the code to prepare the data (see [generate_fetal.py](https://github.com/farrell236/SVRnet/blob/master/generate_data/generate_fetal.py)), as well as train your own model (see [train_svrnet.py](https://github.com/farrell236/SVRnet/blob/master/train_svrnet.py)). The application designed for here is for fetal brain MRI, you'll need to adapt it to your own use case.

**Comment by Edenkut** [comment]
Thank you for your reply.

**Comment by 35101** [comment]
Hi, I am a third-year student in college. I am very interested in your paper published in TMI. Due to the limitations of its own capabilities (especially the related principles of data generation), great difficulties were encountered in the process of reproduction. I don't know if there is a good way to supplement relevant knowledge. In addition, I wonder if you have time to make more detailed comments on the data update code, thank you very much.
